[build]
  command = """
    set -e
    echo "=== Starting Blog build process ==="

    echo "Enabling pnpm via corepack"
    corepack enable
    corepack prepare pnpm@9 --activate

    echo "Node: $(node --version || true)"
    echo "pnpm: $(pnpm --version || true)"
    echo "Hugo: $(hugo version)"
    echo "Go: $(go version || echo 'Go not available')"

    echo "=== Installing dependencies (if any) ==="
    if [ -f package.json ]; then pnpm install --verbose || true; fi

    echo "=== Running Hugo build ==="
    hugo --gc --minify -b ${URL:-/} --logLevel debug --printI18nWarnings --printPathWarnings

    echo "=== Running Pagefind indexing ==="
    pnpm dlx pagefind --source 'public' --verbose

    echo "=== Build completed successfully ==="
  """
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.150.1"
  NODE_VERSION = "22"
  HUGO_ENABLEGITINFO = "true"
  FORCE_COLOR = "1"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = """
    set -e
    corepack enable
    corepack prepare pnpm@9 --activate
    pnpm install --verbose || true
    hugo --gc --minify --buildFuture -b ${DEPLOY_PRIME_URL} --logLevel debug --printI18nWarnings --printPathWarnings
    pnpm dlx pagefind --source 'public' --verbose
  """

[context.branch-deploy]
  command = """
    set -e
    corepack enable
    corepack prepare pnpm@9 --activate
    pnpm install --verbose || true
    hugo --gc --minify -b ${DEPLOY_PRIME_URL} --logLevel debug --printI18nWarnings --printPathWarnings
    pnpm dlx pagefind --source 'public' --verbose
  """

[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"
  [plugins.inputs]
    debug = true
